// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcEHPSgfOvAkWjojWaNYP1DDwLVO8JkzI',
    appId: '1:138538513021:web:5fe1dc3dc5b6fa5bcb7714',
    messagingSenderId: '138538513021',
    projectId: 'flutter-webrtc-83131',
    authDomain: 'flutter-webrtc-83131.firebaseapp.com',
    storageBucket: 'flutter-webrtc-83131.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB76QuGT15sDXy2mJnVDyBCD_EIOFXvsAU',
    appId: '1:138538513021:android:a529543b1bcb4409cb7714',
    messagingSenderId: '138538513021',
    projectId: 'flutter-webrtc-83131',
    storageBucket: 'flutter-webrtc-83131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4cfLIkfZARDbNIPQbbLbnuHT2x9U8gpA',
    appId: '1:138538513021:ios:3e8ada30d0d9d03ccb7714',
    messagingSenderId: '138538513021',
    projectId: 'flutter-webrtc-83131',
    storageBucket: 'flutter-webrtc-83131.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4cfLIkfZARDbNIPQbbLbnuHT2x9U8gpA',
    appId: '1:138538513021:ios:3fd8a484b10406d6cb7714',
    messagingSenderId: '138538513021',
    projectId: 'flutter-webrtc-83131',
    storageBucket: 'flutter-webrtc-83131.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtcTutorial',
  );
}
