// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGBPnhUUakAdifkjCYxyYXSr_k4599zho',
    appId: '1:315148119581:web:1f8759a4db211eb584a0f4',
    messagingSenderId: '315148119581',
    projectId: 'streamflare-67e84',
    authDomain: 'streamflare-67e84.firebaseapp.com',
    storageBucket: 'streamflare-67e84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqg7qxU0dRoV7V1vJzpAGZGgm3ka3IcBg',
    appId: '1:315148119581:android:ba846318d39fc97784a0f4',
    messagingSenderId: '315148119581',
    projectId: 'streamflare-67e84',
    storageBucket: 'streamflare-67e84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQbUHfI-60qStSZOmzk62I--5GmhjN74I',
    appId: '1:315148119581:ios:c5cb778f4049a22484a0f4',
    messagingSenderId: '315148119581',
    projectId: 'streamflare-67e84',
    storageBucket: 'streamflare-67e84.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQbUHfI-60qStSZOmzk62I--5GmhjN74I',
    appId: '1:315148119581:ios:64b71af91311f8ad84a0f4',
    messagingSenderId: '315148119581',
    projectId: 'streamflare-67e84',
    storageBucket: 'streamflare-67e84.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtcTutorial',
  );
}
